version: '3.8'

services:
  discord:
    image: volkunus/dgs-info-bot:latest
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
    volumes:
      - ./bot-data:/usr/src/app
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    command: ["node", "bot.js"]
    restart: always
